name = input()
b = (name.split(' '))
surname = (b[0])
c = (b[1])
f = (b[2])
name_letter1 =(list(c))
help1 =(name_letter1[0])
name_letter2 = (list(f))
help2 = (name_letter2[0])
print (surname + ' ' + help1 + '.' + help2 + '.')